# MockServer Configuration
mockserver.logLevel=INFO
mockserver.disableSystemOut=false
mockserver.corsAllowOrigin=*
mockserver.corsAllowMethods=CONNECT, DELETE, GET, HEAD, OPTIONS, POST, PUT, PATCH, TRACE
mockserver.corsAllowHeaders=Allow, Content-Encoding, Content-Length, Content-Type, ETag, Expires, Last-Modified, Location, Server, Vary, Authorization